### ISSUE TITLE
Add systemd (selinux) script to allow redis to serve drupal

### ISSUE THREAD

**Issue by mrdrewkeller** [jeff1evesque/drupal-demonstration#497]
When the Vagrant box is initialized the command below must be run in order for redis to work:

```bash
sudo /usr/sbin/setsebool httpd_can_network_connect=1
```

**Comment by jeff1evesque** [comment]
We'll need to create a systemd script, contained within an `.erb` template for puppet to define the service. This template script, will need the following logic:

```bash
sudo /usr/sbin/setsebool httpd_can_network_connect=1
```
